### ISSUE TITLE
Do not rename column names when importing data with `playbase::read.as_matrix`

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#511] opened 2023-06-22 10:05 UTC
playbase::read.as_matrix is renaming similar column names with a number, this should not happen! The checks I designed will catch this and report to user and raise error without crashing platform!
```
Browse[2]> df0 <- playbase::read.as_matrix(fn2)
Browse[2]> colnames(df0)
 [1] "notact_004"   "notact_007"   "notact_008"   "notact_009"   "notact_010"
 [6] "notact_011"   "notact_014"   "act12h_018"   "act12h_019"   "act12h_020"
[11] "act24h_023"   "act48h_026"   "act48h_027"   "act72h_028"   "act72h_029"  
[16] "act72h_030"   "act96h_032"   "act96h_034"   "act96h_034.1"
```

**Comment by phisanti** [comment] 2023-06-23 08:37
Cannot repoduce. I tried the followig:

```r
d <- data.frame(a = 0:5, a = 5:10, a = 10:15, b = 0:5, b = 5:10,b = 10:15, check.names = F)
fwrite(d, "testtable.csv")

# test plain fread
d2 <- fread('testtable.csv')
d2
>   a  a  a b  b  b
1: 0  5 10 0  5 10
2: 1  6 11 1  6 11
3: 2  7 12 2  7 12
4: 3  8 13 3  8 13
5: 4  9 14 4  9 14
6: 5 10 15 5 10 15

# test fread with args
d3 <- fread('testtable.csv', check.names=FALSE, header=TRUE, blank.lines.skip=TRUE, stringsAsFactors=FALSE)))
d3
 >  a  a  a b  b  b
1: 0  5 10 0  5 10
2: 1  6 11 1  6 11
3: 2  7 12 2  7 12
4: 3  8 13 3  8 13
5: 4  9 14 4  9 14
6: 5 10 15 5 10 15

# Test read.as_matrix
read.as_matrix <- function(file)
    {
        ## read delimited table automatically determine separator. allow      
        ## duplicated rownames. This implements with faster fread.
        x0 <- data.table::fread(file=file, check.names=FALSE, header=TRUE,    
                                blank.lines.skip=TRUE, stringsAsFactors=FALSE)
        x <- NULL
        sel <- which(!as.character(x0[[1]]) %in% c(""," ","NA","na",NA))      
        length(sel)
        if(length(sel)) {
            x <- as.matrix(x0[sel, -1 ,drop=FALSE])  ## always as matrix
            rownames(x) <- x0[[1]][sel]
        }
        return(x)
    }
d4 <- read.as_matrix(filepath)
d4
>   a  a b  b  b
0  5 10 0  5 10
1  6 11 1  6 11
2  7 12 2  7 12
3  8 13 3  8 13
4  9 14 4  9 14
5 10 15 5 10 15

```

Let me know if the example looks correct, or if you have a way to reproduce the bug.

**Comment by ivokwee** [comment] 2023-06-23 14:30
Confirmed. See below. However, I think the behaviour is preferred. Should not crash the app because only samples columns that are in sample.csv will be included. If there are two columns with same name, which one do you take? In this case the first one matches.

```
X <- playbase::COUNTS 
X <- cbind(X, act96h_034=X[,"act96h_034"])
colnames(X)
write.csv(X, file="counts.csv")
df0 <- playbase::read.as_matrix("counts.csv")
```

**Comment by mauromiguelm** [comment] 2023-06-27 16:21
I think this a common issue users may have, where technical replicates will have the same name, for example.

We have some options to handle that:
1. `warning` the user that we have duplicates and telling the user we will average them.
2. raise an `error` and ask the user to correct.
3. `today's implementation` Not do anything, this will lead to those samples being considered separate samples.

Out of these options for simplicity I prefer (1), but my guess is that we need to find a way to get the column names outside `read.as_matrix` function.

@ivokwee, whats your take on this?

**Comment by ivokwee** [comment] 2023-07-20 20:43
let's close.

**Closed by ivokwee** 2023-07-20 20:43 UTC
Labels: bug
