### ISSUE TITLE
Error in `playbase::detectBatchEffects`

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#1070] opened 2024-09-02 14:33 UTC
dataset: **Geiger et al., Cell 2016**

When in the upload module, select `remove batch effects`

[mmc2-metabolomics_samples_no_duplicates_clean.csv](https://github.com/user-attachments/files/16838792/mmc2-metabolomics_samples_no_duplicates_clean.csv)
[mmc2-metabolomics_counts_no_duplicates.csv](https://github.com/user-attachments/files/16838793/mmc2-metabolomics_counts_no_duplicates.csv)

```r
    136: h
  135: .handleSimpleError
  134: playbase::detectBatchEffects
  133: playbase::get_model_parameters
  132: eventReactiveValueFunc
  131: ..stacktraceon..
  130: valueFunc
  129: ..stacktraceon..
  128: contextFunc
```

**Comment by ESCRI11** [comment] 2024-09-05 12:28
@mauromiguelm Can't reproduce, can you provide further info?

**Comment by ivokwee** [comment] 2024-09-06 15:05
what contrast did you use? with these contrasts I have no problems
![image](https://github.com/user-attachments/assets/a5bc1489-d4ec-444f-975e-3074a20754e8)

**Comment by ivokwee** [comment] 2024-09-06 19:55
closing issue. please reopen if persists.

**Closed by ivokwee** 2024-09-06 19:55 UTC
Labels: bug
